from django.db import models

# Create your models here.
class EvOlf(models.Model):
    EvOlf_ID = models.CharField(max_length=100, null=True, blank=True)
    Class = models.CharField(max_length=100, null=True, blank=True)
    Species = models.CharField(max_length=100, null=True, blank=True)
    Receptor_ID = models.CharField(max_length=100, null=True, blank=True)
    Receptor = models.CharField(max_length=200, null=True, blank=True)
    UniProt_ID = models.CharField(max_length=100, null=True, blank=True)
    Mutation_Status = models.CharField(max_length=50, null=True, blank=True)
    Mutation = models.CharField(max_length=200, null=True, blank=True)
    Mutation_Impact = models.CharField(max_length=200, null=True, blank=True)
    Sequence = models.TextField(null=True, blank=True)
    Receptor_SubType = models.CharField(max_length=100, null=True, blank=True)
    Ligand_ID = models.CharField(max_length=100, null=True, blank=True)
    Ligand = models.CharField(max_length=200, null=True, blank=True)
    SMILES = models.TextField(null=True, blank=True)
    CID = models.CharField(max_length=100, null=True, blank=True)
    ChEMBL_ID = models.CharField(max_length=100, null=True, blank=True)
    InChiKey = models.CharField(max_length=100, null=True, blank=True)
    InChi = models.TextField(null=True, blank=True)
    IUPAC_Name = models.TextField(null=True, blank=True)
    Method = models.CharField(max_length=200, null=True, blank=True)
    Expression_System = models.CharField(max_length=200, null=True, blank=True)
    Parameter = models.CharField(max_length=100, null=True, blank=True)
    Value = models.CharField(max_length=50, null=True, blank=True)
    Unit = models.CharField(max_length=50, null=True, blank=True)
    Source = models.CharField(max_length=200, null=True, blank=True)
    Model = models.CharField(max_length=200, null=True, blank=True)
    Image = models.URLField(null=True, blank=True)
    Structure_3D = models.URLField(null=True, blank=True)
    PubChem_Link = models.URLField(null=True, blank=True)
    Source_Links = models.TextField(null=True, blank=True)
    UniProt_Link = models.URLField(null=True, blank=True)
    Comments = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.EvOlf_ID or str(self.id)
