# Generated by Django 5.2.7 on 2025-10-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EvOlf_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('Class', models.CharField(blank=True, max_length=100, null=True)),
                ('Species', models.CharField(blank=True, max_length=100, null=True)),
                ('Receptor_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('Receptor', models.CharField(blank=True, max_length=200, null=True)),
                ('UniProt_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('Mutation_Status', models.CharField(blank=True, max_length=50, null=True)),
                ('Mutation', models.CharField(blank=True, max_length=200, null=True)),
                ('Mutation_Impact', models.CharField(blank=True, max_length=200, null=True)),
                ('Sequence', models.TextField(blank=True, null=True)),
                ('Receptor_SubType', models.CharField(blank=True, max_length=100, null=True)),
                ('Ligand_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('Ligand', models.CharField(blank=True, max_length=200, null=True)),
                ('SMILES', models.TextField(blank=True, null=True)),
                ('CID', models.CharField(blank=True, max_length=100, null=True)),
                ('ChEMBL_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('InChiKey', models.CharField(blank=True, max_length=100, null=True)),
                ('InChi', models.TextField(blank=True, null=True)),
                ('IUPAC_Name', models.TextField(blank=True, null=True)),
                ('Method', models.CharField(blank=True, max_length=200, null=True)),
                ('Expression_System', models.CharField(blank=True, max_length=200, null=True)),
                ('Parameter', models.CharField(blank=True, max_length=100, null=True)),
                ('Value', models.CharField(blank=True, max_length=50, null=True)),
                ('Unit', models.CharField(blank=True, max_length=50, null=True)),
                ('Source', models.CharField(blank=True, max_length=200, null=True)),
                ('Model', models.CharField(blank=True, max_length=200, null=True)),
                ('Image', models.URLField(blank=True, null=True)),
                ('Structure_3D', models.URLField(blank=True, null=True)),
                ('UniProt_Link', models.URLField(blank=True, null=True)),
                ('ChEMBL_Link', models.URLField(blank=True, null=True)),
                ('PubChem_Link', models.URLField(blank=True, null=True)),
                ('Ensembl_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('Ensembl_Link', models.URLField(blank=True, null=True)),
                ('Comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
