# Generated by Django 5.2.7 on 2025-10-31 02:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Receptor",
            new_name="Evolf",
        ),
    ]
