# Generated by Django 5.2.7 on 2025-11-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_receptor_evolf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evolf',
            old_name='Comment',
            new_name='Comments',
        ),
        migrations.RemoveField(
            model_name='evolf',
            name='ChEMBL_Link',
        ),
        migrations.RemoveField(
            model_name='evolf',
            name='Ensembl_ID',
        ),
        migrations.RemoveField(
            model_name='evolf',
            name='Ensembl_Link',
        ),
        migrations.AddField(
            model_name='evolf',
            name='Source_Links',
            field=models.TextField(blank=True, null=True),
        ),
    ]
